name: CI

on: push

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - "8.8.4"
        cabal:
          - "3.2"
        os:
          - windows-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v2
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

      - name: Update Hackage index
        run: cabal v2-update

      - name: Build
        run: |
          cabal v2-build -j all
          cabal v2-install exe:csv-manager --install-method=copy --installdir=./build
          7z a csv-manager.${{ matrix.os }}.ghc-${{ matrix.ghc }}.zip ./build/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: csv-manager.${{ matrix.os }}.ghc-${{ matrix.ghc }}.zip
